## Install and configure nginx

- hosts: localhost

  tasks:
  - name: Install nginx
    yum: name=nginx state=present
    tags: nginxinstall

  - name: Create the document root directory
    file: path=/var/www/html state=directory owner=root group=root mode=0755
    tags: documentroot

  - name: Create the document root
    template:
        src: "/tmp/index.html.j2"
        dest: "/var/www/html/index.html"
        owner: root
        group: root
        mode: 0644
    tags: indexdocument

  - name: Configure nginx to display a host-dependent page
    template:
        src: "/tmp/default.conf.j2"
        dest: "/etc/nginx/conf.d/default.conf"
        owner: root
        group: root
        mode: 0644
    tags: nginxconfig

